@startuml AD_1.0

left header
<font color=000 size=18><b>Package:</b> AD_1.0

<font color=000 size=16><b>ID:</b> UC_3
<font color=000 size=16><b>Назва:</b> Проходження опитування
<font color=000 size=16><b>Учасники:</b> Експерт, Система
<font color=000 size=16><b>Передумови:</b> Відсутні
<font color=000 size=16><b>Результат:</b> Інформування про успішне завершення опитування
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_3.1 Опитування відсутнє
<font color=000 size=16> EX_3.2 Користувач достроково покинув опитування

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Експерт|
start
: Запускає процес проходження опитування;


|Система|
: Отримує ідентифікатор експерта;

note right #aaffaa

Система по ідентифікату,
який був створенний під час регістрації,
шукаэ експерта
(див. UC_1).

<font color=red><b> Можливо EX_3.1.

end note

split
:надсилає персоналізовані питання 
для проходження опитування;

note left #aaffaa
див. UC_7.4
end note

split again
:надсилає питання 
для проходження опитування,
створені автором;

note right #aaffaa
див. UC_8
end note
end split

|Експерт|
:Відповідає на поставлені запитання;

note left #LightBlue
<font color=red><b> Можливо EX_3.1.
end note

:Інформує систему про 
повне проходження опитування;

note left #LightBlue
Експерт відповів
на всі обов'язкові запитаня
та натиснув 
"Надіслати результати опитування"
end note


|Система|
:Зберігає файл з даними пройденого опитування;

note right #aaffaa
До метаданих файлу повино ходити:
    Посилання на опитування
    Експерт, який пройшов опитування
    Дата проходження опитування
Файл повинен складатися по шаблону: 
    "Номер питання - відповідь"
end note

:До акаунта експерта додається позначка про проходження опитування;

note right #aaffaa
див. UC_11.1.1.2.4
end note
:Генерує повідомлення про успішне завершення опитування;
|Експерт|
stop;

right footer


Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml

