
@startuml UCD_3.0

right header
<font size=24 color=black>Package:<b> UCD_3.0

end header

title
<font size=18 color=black>UC_7. Редагувати опитування
<font size=16 color=black>Діаграма прецедентів


end title

package UCD_1.0 {
usecase "<b>UC_7</b>\nРедагувати опитування" as UC_7 #Green
}

actor "Редактор" as Collaborator
usecase "<b>UC_7.1</b>\nЗмінювати типи \n поставлених питань" as UC_7.1  #LightGreen
usecase "<b>UC_7.2</b>\nДодавати мультимедійні \n запитання"  as UC_7.2 #LightGreen
usecase "<b>UC_7.3</b>\nЗмінювати структуру \n опитування" as UC_7.3  #LightGreen
usecase "<b>UC_7.4</b>\nСтворювати персоналізовані \n питання" as UC_7.4  #LightGreen

Collaborator -> UC_7

UC_7.2 -u-|> UC_7
UC_7.3 --|> UC_7
UC_7.4 --|> UC_7
UC_7.1 -|> UC_7

    note right of UC_7.2 #eeffee
        Використання малюнків,
        фотографії, аудіофалів, відео
    end note

right footer

Аналітичний портал. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
 