ml /c /coff "8-03-IP84-Golubov-dll-with-point.asm"
link /DLL /subsystem:windows /DEF:"8-03-IP84-Golubov-def-with-point.def" "8-03-IP84-Golubov-dll-with-point.obj"
ml /c /coff "8-03-IP84-Golubov-dll-without-point.asm"
link /DLL /DEF:"8-03-IP84-Golubov-def-without-point.def" /NOENTRY "8-03-IP84-Golubov-dll-without-point.obj"
ml /c /coff "8-03-IP84-Golubov-static-with.asm"
link /subsystem:windows "8-03-IP84-Golubov-static-with.obj"
ml /c /coff "8-03-IP84-Golubov-static-without.asm"
link /subsystem:windows "8-03-IP84-Golubov-static-without.obj"
ml /c /coff "8-03-IP84-Golubov-dynamic-with.asm"
link /subsystem:windows "8-03-IP84-Golubov-dynamic-with.obj"
ml /c /coff "8-03-IP84-Golubov-dynamic-without.asm"
link /subsystem:windows "8-03-IP84-Golubov-dynamic-without.obj"