ml /c /coff "8-16-IP84-Sapbiev-with.asm"
link /DLL /subsystem:windows /DEF:"8-16-IP84-Sapbiev-with.def" "8-16-IP84-Sapbiev-with.obj"
ml /c /coff "8-16-IP84-Sapbiev-without.asm"
link /DLL /DEF:"8-16-IP84-Sapbiev-without.def" /NOENTRY "8-16-IP84-Sapbiev-without.obj"
ml /c /coff "8-16-IP84-Sapbiev-static-with-point.asm"
link /subsystem:windows "8-16-IP84-Sapbiev-static-with-point.obj"
ml /c /coff "8-16-IP84-Sapbiev-static-without-point.asm"
link /subsystem:windows "8-16-IP84-Sapbiev-static-without-point.obj"
ml /c /coff "8-16-IP84-Sapbiev-dynamic-with-point.asm"
link /subsystem:windows "8-16-IP84-Sapbiev-dynamic-with-point.obj"
ml /c /coff "8-16-IP84-Sapbiev-dynamic-without-point.asm"
link /subsystem:windows "8-16-IP84-Sapbiev-dynamic-without-point.obj"